apiVersion: apps/v1
kind: Deployment
metadata:
  name: bms-deployment
  namespace: bms-ns
  labels:
    app: bms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bms-container
        image: saurav2059/book-my-show:v1.0.3
        ports:
        - containerPort: 3000

